version: '3.5'

services:
  traefik:
    # This traefik image is Let's Encrypt ready and doesn't let plain HTTP traffic pass.
    image: tiagostutz/traefik-letsencrypt:1.6 # Traefik docker image with Let's Encrypt ready for http challenge
    environment:
      - LETS_ENCRYPT_TEST_MODE=false
      - LETS_ENCRYPT_EMAIL=your@email.com
      - SWARM_MODE=true    
    ports:
      - 80:80     # The HTTP port
      - 443:443   # The HTTPS port
      - 3030:8080 # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    networks:
      - metrics-net
      - traefik-net

networks:
  traefik-net:
    external: true
    # "docker network create traefik-net --scope swarm -d overlay"
  metrics-net:
    external: true
    # "docker network create metrics-net --scope swarm -d overlay"

